"""empty message

Revision ID: 068f8c4ab4e2
Revises: 
Create Date: 2019-10-31 16:27:53.183057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068f8c4ab4e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_uuid', sa.String(length=36), nullable=True),
    sa.Column('id_stripe', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('image_file', sa.String(length=36), nullable=False),
    sa.Column('password', sa.String(length=87), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_uuid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_uuid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('publish_date', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_uuid'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('user')
    # ### end Alembic commands ###
