"""empty message

Revision ID: fa94d18268f4
Revises: 068f8c4ab4e2
Create Date: 2019-10-31 16:30:41.692706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa94d18268f4'
down_revision = '068f8c4ab4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
